# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25333a0441407c99c58994ff4ceb18445dbb7928efa33d64aa3dffce383bf9e9954a6aac35bc156bcc761860aefe4ff46ad13cd6be0c55dfcd454f7a7d65deec

test:
  secret_key_base: 319bc470b49447e625ca490dc062b323ea248c56e61b47878936a8aa65d7e18c277958471154b43063a50677322f469e646ef257dbd2bf725b9e1769b6fc2931

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
